# .streamlit/secrets.toml

# Identificação do Projeto Google Cloud
GOOGLE_PROJECT_ID = "rota-da-seda-478119"
GOOGLE_LOCATION = "europe-west4"

# Credenciais do Banco de Dados (Já devem estar aqui se você usava antes, se não, adicione)
DATABASE_URL='postgresql://neondb_owner:npg_AzWeQ81KkGwH@ep-purple-queen-adncejfa-pooler.c-2.us-east-1.aws.neon.tech/neondb?sslmode=require'